#!/bin/bash

declare -A confedit_list
confedit_list[alacritty]="$HOME/.config/alacritty/alacritty.yml"
confedit_list[dunst]="$HOME/.config/dunst/dunstrc"
confedit_list[flameshot]="$HOME/.config/flameshot/flameshot.ini"
confedit_list[picom]="$HOME/.config/picom/picom.conf"
confedit_list[ssh]="$HOME/.ssh/config"
confedit_list[xmonad]="$HOME/.config/xmonad/xmonad.hs"
confedit_list[xmobar]="$HOME/.xmobarrc0"
confedit_list[zsh]="$HOME/.zshrc"
confedit_list[bash]="$HOME/.bashrc"

DMENU="dmenu -i -h 25 -l 20 -p"
DMEDITOR="emacsclient -c -a emacs"

main() {
    # Clean options array making sure that the files exist
    declare -A _clean_list
    # As this is loaded from other file it is technically not defined
    # shellcheck disable=SC2154
    for i in "${!confedit_list[@]}"; do
        [[ -f ${confedit_list["${i}"]} ]] && _clean_list["${i}"]=${confedit_list["${i}"]}
    done

    # Piping the above array (cleaned) into dmenu.
    # We use "printf '%s\n'" to format the array one item to a line.
    choice=$(printf '%s\n' "${!_clean_list[@]}" | sort | ${DMENU} 'Edit config:' "$@")

    # What to do when/if we choose a file to edit.
    if [ "$choice" ]; then
        cfg=$(printf '%s\n' "${_clean_list["${choice}"]}")
        # shellcheck disable=SC2154
        $DMEDITOR "$cfg"
    # What to do if we just escape without choosing anything.
    else
        echo "Program terminated." && exit 0
    fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
