# alacritty.toml

live_config_reload = true

[env]
TERM = "alacritty"

[window]
decorations     = "None"
dynamic_padding = false
dynamic_title   = true
opacity         = 0.8
startup_mode    = "Maximized"
title           = "Alacritty"

[window.dimensions]
columns = 0
lines   = 0

[window.padding]
x = 6
y = 6

[scrolling]
history = 6000
multiplier = 3

[font]
builtin_box_drawing = false
size                = 8.0

[font.bold]
family = "Ubuntu Mono"
style  = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[font.normal]
family = "Ubuntu Mono"
style  = "Regular"

[font.italic]
family = "Ubuntu Mono"
style  = "Italic"

[font.bold_italic]
family = "Ubuntu Mono"
style  = "Bold Italic"

[colors.primary]
# background = "#090300"
# foreground = "#a5a2a2"

[colors.cursor]
cursor = "CellForeground"
text   = "CellBackground"

[colors.normal]
black   = "#090300"
white   = "#a5a2a2"
blue    = "#01a0e4"
red     = "#db2d20"
cyan    = "#b5e4f4"
green   = "#01a252"
magenta = "#a16a94"
yellow  = "#fded02"

[colors.bright]
black   = "#5c5855"
blue    = "#01a0e4"
cyan    = "#b5e4f4"
green   = "#01a252"
magenta = "#a16a94"
red     = "#db2d20"
white   = "#f7f7f7"
yellow  = "#fded02"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text   = "CellBackground"

[colors.search.matches]
background = "CellBackground"
foreground = "CellForeground"

[colors.search.focused_match]
background = "CellBackground"
foreground = "CellForeground"

[colors.hints.start]
background = "CellBackground"
foreground = "CellForeground"

[colors.hints.end]
background = "CellBackground"
foreground = "CellForeground"

[colors.footer_bar]
background = "#C0C5CE"
foreground = "#232323"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.selection]
background = "CellForeground"
text       = "CellBackground"

# [bell]
# animation = "EaseOutExpo"
# color     = "#C0C5CE"
# command   = "None"
# duration  = 0

[selection]
save_to_clipboard     = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
unfocused_hollow = true
vi_mode_style    = "None"

[cursor.style]
shape = "Block"
blinking = "On"

[[keyboard.bindings]]
action = "ToggleViMode"
key    = "Space"
mods   = "Alt|Shift"

[[keyboard.bindings]]
action = "Paste"
key    = "V"
mods   = "Alt|Shift"

[[keyboard.bindings]]
action = "Copy"
key    = "C"
mods   = "Alt|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key    = "PageUp"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key    = "PageDown"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key    = "Home"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key    = "End"
mods   = "Shift"

[mouse]
hide_when_typing = true

[debug]
highlight_damage   = false
log_level          = "Warn"
persistent_logging = false
print_events       = false
render_timer       = false
